apiVersion: v1
kind: Service
metadata:
  name: flask-k8s-service
spec:
  type: NodePort
  ports:
    - protocol: TCP  
      port: 80
      targetPort: 5000
      nodePort: 30036
  selector:
    app: flask-k8s